name: loyaltty_customer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.2.0
#  image_picker: ^1.0.2
  dio: ^5.3.2
  dotted_border: ^2.0.0+3
  country_code_picker: ^3.0.0
  pin_code_text_field: ^1.8.0
#  stop_watch_timer: ^3.0.1
  country: ^3.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  cached_network_image: ^3.2.3
  heroicons: ^0.9.0
  qr_flutter: ^4.1.0
#  lottie: ^2.6.0
  devicelocale: ^0.7.0
  lottie: ^2.6.0
  confetti: ^0.7.0
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  awesome_notifications: ^0.8.2
#  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_icons:
  # Command Line to change the icon
  # flutter pub run flutter_launcher_icons:main
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  # Command Line to set native splash
  # flutter pub run flutter_native_splash:create
  #
  # color & background_image attribute
  #   - color : to select splash background color
  #   - background_image : to select splash background image
  #   - choose between it or background_image
  # color: "#171612"
  background_image: "assets/images/background.png"
  # center splash icon
  image: assets/images/logo.png

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf